### ISSUE TITLE
Provide left handed orientation

### ISSUE THREAD

**Issue by leehbi** [txels/fretboard#2]
Is it easy to orientate fret board for left handed players.  Possibly my passing in parameter to drawAll()

**Comment by txels** [comment]
That is a great suggestion. I don't think it should be hard, I will take a look.

I'm curious as to how you found out about this project, and how you're using it. This Issue came as a nice surprise as I don't remember having publicised the project, so it makes me happy to see people giving it a try.

**Comment by leehbi** [comment]
Trying to learn the fretboard - was going to try and develop something like this to help me but it seems you've already done it

**Comment by txels** [comment]
Hey, it took a little bit more effort than expected, but I've added this to the master branch. Enjoy!

**Comment by leehbi** [comment]
Good job looks really good.
